services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auction
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
  pgdata: